/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package New;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.bean.Usuario;
import model.dao.UsuarioDAO;


/**
 *
 * @author Lukas Souza
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTemail = new javax.swing.JTextField();
        jPasswordFieldsenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(845, 490));
        setPreferredSize(new java.awt.Dimension(800, 490));
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonOK.setBackground(new java.awt.Color(230, 126, 34));
        jButtonOK.setBackground(new java.awt.Color(211, 84, 0));
        jButtonOK.setFont(new java.awt.Font("arial", 14, 18));
        jButtonOK.setForeground(java.awt.Color.white);
        jButtonOK.setText("Entrar");
        jButtonOK.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonOK.setBorderPainted(false);
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOK);
        jButtonOK.setBounds(410, 320, 290, 40);

        jPanel1.setBackground(new java.awt.Color(0, 3, 47));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1822508809-1.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel6.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 260, 460);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.orange);
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 190, 130, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.orange);
        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 100, 80, 50);

        jTemail.setColumns(0);
        jTemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTemail.setBorder(null);
        jTemail.setFocusCycleRoot(true);
        jTemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTemailFocusGained(evt);
            }
        });
        jTemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTemailActionPerformed(evt);
            }
        });
        getContentPane().add(jTemail);
        jTemail.setBounds(400, 160, 300, 30);

        jPasswordFieldsenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordFieldsenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldsenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldsenha);
        jPasswordFieldsenha.setBounds(400, 260, 300, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/simple-wood-widescreen.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 0, 590, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        UsuarioDAO usuariodao = new UsuarioDAO();
        
        if(usuariodao.checkLugin(jTemail.getText(), jPasswordFieldsenha.getText())){
            new Menu().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Password Incorreto !!!");
        }
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jTemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTemailActionPerformed

    private void jTemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTemailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTemailFocusGained

    private void jPasswordFieldsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldsenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldsenha;
    private javax.swing.JTextField jTemail;
    // End of variables declaration//GEN-END:variables
}
